CREATE DATABASE assignmentDB;

USE assignmentDB;

CREATE TABLE user (
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(191) NOT NULL, email VARCHAR(191) NOT NULL, password VARCHAR(191) NOT NULL
);

CREATE TABLE book (
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL, price INTEGER NOT NULL, description TEXT(191),
);

INSERT INTO user ()